### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SakshiZ9**

### CODE REVIEW

**Comment by Arsenic-ATG** [comment]
did you changed anything ? 🧐

Also remove the build ([Qt-calculator/build-Calculator-Desktop_Qt_5_15_2_MinGW_64_bit-Debug](https://github.com/SakshiZ9/Qt-calculator/tree/master/Qt-calculator/build-Calculator-Desktop_Qt_5_15_2_MinGW_64_bit-Debug) ) files from your repo, this is your system specific files and will void the purpose of having a platform independent project. 🙂

**Review by Arsenic-ATG — CHANGES_REQUESTED** [review]
~did you changed anything ? 🧐~

Also remove the build ([Qt-calculator/build-Calculator-Desktop_Qt_5_15_2_MinGW_64_bit-Debug](https://github.com/SakshiZ9/Qt-calculator/tree/master/Qt-calculator/build-Calculator-Desktop_Qt_5_15_2_MinGW_64_bit-Debug) ) files from your repo, this is your system specific files and will void the purpose of having a platform independent project. 🙂

**Comment by SakshiZ9** [comment]
Yes,I changed the position of buttons and added () to make calculations easy.

**Comment by Arsenic-ATG** [comment]
ok then just remove the build files and your pull request will be good to go .

**Comment by SakshiZ9** [comment]
I have removed the build files. Can u kindly check?

**Comment by Arsenic-ATG** [comment]
no, I think you deleted your entire [fork](https://www.earthdatascience.org/workshops/intro-version-control-git/about-forks/) instead, because now it is inaccessible.

**Comment by vivek80801** [comment]
@SakshiZ9 

- Create a new fork of this repo
- Copy all  [changes](https://github.com/Arsenic-ATG/Qt-calculator/pull/13/files "file changes")
   - If Changes are not visible click on **load diff**
- remove unnecessary files.
- commit your changes
- push your commit to github.

**Comment by Arsenic-ATG** [comment]
⚠️ **due to long inactivity**, this PR has been closed

**Pull request closed without merging**
